### ISSUE TITLE
Add Bitcoin daily inflation to metrics page

### ISSUE THREAD

**Issue by nbtb415** [running-coder/nanolooker#14]
Love your site! One potential addition to the metrics next to the bitcoin transaction fees paid that day would be the number and market value of bitcoins mined that day (bitcoin daily inflation) as a stark contrast to nano. You could even sum this with transaction fees paid for a "value diluted from bitcoin holders last 24 hours" or something.

**Comment by tombertrand** [comment]
Could be interesting to have a page and compare a few metrics nano vs btc, in terms of inflation / fees / energy usage / user base / etc and see that order of magnitude
