### ISSUE TITLE
Display Network CPS and Node CPS

### ISSUE THREAD

**Issue by tombertrand** [running-coder/nanolooker#16]
**Is your feature request related to a problem? Please describe.**
To have more accurate metrics on the explorer, we'd need to be able to compare CPS happening on the network VS CPS happening on the NL node.

**Describe the solution you'd like**
On the timeline, display the network CPS metric.

Reference: https://discord.com/channels/370266023905198083/370266023905198085/848910021677154347
Data: https://nanoticker.info/json/stats.json

![image](https://user-images.githubusercontent.com/19352322/120198355-febbd800-c1ef-11eb-9f40-c0f20f6d1749.png)

**Comment by filipesmedeiros** [comment]
Is someone taking this already? I'd love to contribute!

**Comment by tombertrand** [comment]
Added in 274e62e
