### ISSUE TITLE
UI Disappears on Distribution with `Log Scale` on and `Include known exchanges` off

### ISSUE THREAD

**Issue by mkral** [running-coder/nanolooker#3]
**Describe the bug**
The entire UI disappears on Distribution when you toggle `Log Scale` on and `Include known exchanges` off

**To Reproduce**
1. Go to Explore -> Distribution
2. Turn `Log Scale` toggle on
3.  Turn `Include known exchanges` toggle off
4. The entire UI turns white and you have to refresh to continue using 

**Expected behavior**
UI should still be visible and show the correlating data

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 87.0

**Comment by tombertrand** [comment]
Thanks for flagging the issue, should be resolved in 2464276 and available in a few minutes
