### ISSUE TITLE
All my mines from was STOLEN. 

### ISSUE THREAD

**Issue by mwuaaah4u** [running-coder/nanolooker#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

-hello its my 1st time to try to use the (2miners to nano withdrawal) i thought that the nano address that given to me was automatically well deposit to my nano wallet. then for 3 days i visited may nano wallet and its still  "0"  coin.  so ive go to nanolooker to look for my converted mines. and now im still on my mix emotions stage. i felt -sad mad and most of all so big DIS APPOINTMENT!!!!!
![Screenshot_20211106-075011](https://user-images.githubusercontent.com/92922939/140590123-880b1776-0952-444a-9961-dc23558aef42.png)
this is the wallet address they gave to me.. ☝️

this is may latest transaction.👇
![Screenshot_20211106-074850_1](https://user-images.githubusercontent.com/92922939/140590280-b48d668a-0f5f-4239-a7b1-15739322143d.png)

Guys i'm beggin on youre help coz idont really know how to edit my wallet address..-( nano_16bnjuwbot3z1u1eyyjxi789bd88a5xibus6qfsa7i3etwjd3t7obqcz1xu6 )-
im just a smaller token miner. 🙏🙏🏼🙏

**Comment by tombertrand** [comment]
Have you followed the instructions from 2miners to correctly setuo your payouts? https://2miners.com/blog/how-to-get-payouts-for-ethereum-mining-without-fees/

Make sure you create yourself a Natrium wallet and use your own nano_ address when launching the mining software. If this was setup correctly I’d suggest you contact the 2miners support and ask then to verify your account was paid correctly.

**Comment by mwuaaah4u** [comment]
how can i launch i only use smartphone...
