### ISSUE TITLE
I'd like to translate nanolooker to polish (manually)

### ISSUE THREAD

**Issue by imalfect** [running-coder/nanolooker#5]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to translate the website to Polish (my native language)

**Describe alternatives you've considered**
none.
**Additional context**
I want to translate it manually as Polish translations by google are really poor

**Comment by tombertrand** [comment]
I've added the base for you to go over if you'd like in #6

**Comment by tombertrand** [comment]
@imalfect Translations are up 👍
