### ISSUE TITLE
Polish language have a lot of translation mistakes.

### ISSUE THREAD

**Issue by MomboteQ** [running-coder/nanolooker#58]
Hello, Polish language have a lot of translation mistakes.
Suggested changes:
1. Język Polski -> Polski
2. Otrzymanie -> Otrzymano
3. Wysyłanie -> Wysłano
4. Utworzone przez: RunningCoder -> Stworzono przez: RunningCoder 
5. Daj Dotację -> Wyślij Dotację
6. Krany Nano -> Kraniki Nano

These are just a few of the things that stand out. I would like to ask for the website to be translated into Polish again.

**Comment by tombertrand** [comment]
Would you be able to open a PR on the [pl.json](https://github.com/running-coder/nanolooker/blob/master/src/i18n/locales/pl.json) file fixing those translations?

**Comment by MomboteQ** [comment]
I fixed everything and created a PR.
